# -*- coding: utf-8 -*-
"""24I2593_Python_Programming (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dymEa0L71VBzoHJzJ5sGVtUo-b6AVlax

Wrong naming
"""

3boolean =True
na-me ="moana"
class ="ahmad"

print(3boolean, na-me, class)

"""Correct Naming"""

boolean=False
name = "ali"
_num= 10
num =10
is_name =10 and 14
is_class =10 and True

print(boolean,name,num,is_name,is_class)
3boolean

"""Task # 02

"""

num1 = int (input("Press 1st number: "))
num2 = int (input("Press 2nd number: "))
sym = input("Press symbol")

if sym == "+":
    print(num1 + num2)

elif sym == "-":
    print(num1 - num2)

elif sym == "*":
    print(num1 * num2)

elif sym == "/":
    print(num1 / num2)

elif sym == "//":
    print(num1 // num2)

elif sym == "**":
    print(num1 ** num2)

else:
    print("Invalid operator")

"""Task # 03"""

num1 = int(input("Press 1st number: "))
num2 = int(input("Press 2nd number: "))
num3 = int(input("Press 3rd number: "))

if num1 > num2 and num1 > num3:
    print("Largest:", num1)

elif num2 > num1 and num2 > num3:
    print("Largest:", num2)

elif num3 > num1 and num3 > num2:
    print("Largest:", num3)

elif num1 == num2 == num3:
    print("All are equal")


if num1 < num2 and num2 < num3:
    print("Numbers are in ascending order")

elif num1 > num2 and num2 > num3:
    print("Numbers are in descending order")

else:
    print("Numbers are not in order")

"""TASK 4"""

num1 = int( input("press 1st no"))
num2 = int( input("press 2nd no"))

print("Before swap ", num1,num2)
temp=num1
num1=num2
num2=temp
print("After swap ", num1,num2)

"""Task 5"""

x, y, z = 5, 10, 15

print(x,y,z)

x, y, z = 10, 5, 15

print(x,y,z)